name: Acoustic
favicon: null
layout_spectrum: 0.27202490414492786
typography_spectrum: 0.6064182461705059
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7335956688039005
  lightness: 0.6420472168829292
  saturation: 0.2563496751245111
  rhythmicContrast: 0.12488474091514945
purpose: []
